[deploy]
bucket = 'cfn-artifacts-cruddur-fun'
region = 'ap-south-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://cruddur.fun'
EnvBackendUrl = 'https://api.cruddur.fun'
DDBMessageTable = 'CrdDdb-DynamoDBTable-1N8UPG92WEMOH'