[deploy]
bucket = 'cfn-artifacts-cruddur-fun'
region = 'ap-south-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:ap-south-1:682666208032:certificate/5b112f52-55f9-4259-9e52-147636f95b52'
NetworkingStack = 'CrdNet'