[deploy]
bucket = 'cfn-artifacts-cruddur-fun'
region = 'ap-south-1'
stack_name = 'CrdFrontend'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:682666208032:certificate/29951725-46bb-4525-b3de-86153755c85e'
WwwBucketName = 'www.cruddur.fun'
RootBucketName = 'cruddur.fun'